id: A66545544
title: Brief Dhāraṇī of Glorious Vajraṇakhī
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:31:10.609893
  last_modified_at: 2022-03-01 06:31:10.609898
